---
- name: Install WordPress, Nginx, and PHP-FPM
  hosts: localhost
  vars_files:
  - group_vars/localhost
  remote_user: root
  become: yes

  roles:
    - common
    - nginx
    - php-fpm
    - wordpress

# - name: Install common tools
#   hosts: elb.wayofthesys.com

#   roles:
#    - common 
