---
- name: Turn off selinux temporarily
  command: setenforce 0  

- name: Turn off selinux permanently
  copy: src=selinux dest=/etc/selinux/config

- name: Turn off iptables temporarily 
  shell: service iptables stop 

- name: Turn off iptables permenantly  
  service: name=iptables enabled=no 

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Install mysql client
  yum: name=mysql.x86_64 state=present

- name: Install mysql python
  yum: name=MySQL-python.x86_64 state=present

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Copy .my.cnf to ~/.my.cnf
  template: src=.my.cnf dest=~/.my.cnf  

- name: Install git 
  yum: name=git state=present

- name: Install python-pip 
  yum: name=python-pip state=present

- name: Install letsencrypt-aws
  git: repo=https://github.com/alex/letsencrypt-aws.git dest=/usr/local/bin
