---
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Set permissions 
  file: path=/srv/wordpress group=wordpress owner=wordpress mode=0755

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} login_host={{ wp_db_hostname }} login_user={{ wp_db_user }} login_password={{ wp_db_password }} state=present

- name: Create WordPress database user
  # mysql_user: name={{ wp_db_name }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host={{ wp_db_hostname }} state=present
  mysql_user: name={{ wp_db_user }} login_host={{ wp_db_hostname }} login_user={{ wp_db_user }} login_password={{ wp_db_password }} password={{ wp_db_password }} state=present

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/ 

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes 

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes

- name: Install wp-cli
  copy: src=wp-cli.phar dest=/usr/local/bin/wp mode=0755
 
- name: Run wp-cli blog install
  shell: /usr/local/bin/wp core install --url="mydomain.com"  --title="Way Of The Sys" --admin_user="admin" --admin_password="Sup3r Dup3r S3cur1 0C0urse" --admin_email="me@example.com" 
  become: yes
  become_user: wordpress

- name: Check posts
  shell: /usr/local/bin/wp post list|grep "Awesome Postrock Music"
  register: wp_post1_check
  ignore_errors: True
  become_user: wordpress

- name: Create post
  shell: /usr/local/bin/wp post create --post_type=post --post_status=publish --post_title="Awesome Postrock Music" --post_content="[embed]https://youtu.be/Mn71Nc8-1w0[/embed]"
  become: yes
  become_user: wordpress
  when: wp_post1_check|failed

